import type { Inventory, Unit } from "@/lib/types";
import data from "./canonical-units.json";

/**
 * CANONICAL UNIT INVENTORY.
 *
 * Generated by `npm run import:inventory -- <export.csv>` from Limar's sales-system export
 * (see docs/INVENTORY_IMPORT.md). Never edit canonical-units.json by hand and never invent units:
 * it is empty until a real export is imported. Every surface — explorer, comparison, Pathfinder
 * matches, enquiry validation, structured data — reads from here.
 *
 * `price` stays null unless Limar publishes a current list price.
 */
export const canonicalInventory: Inventory = {
  source: "canonical",
  asOf: data.asOf,
  units: data.units as Unit[],
};

/**
 * Availability known at development level while the unit schedule is pending.
 * `null` = residences are available but the count is not confirmed.
 */
export const canonicalAvailability: Record<string, number | null> = {
  "terrace-heights": null,
  "parkview-residences": 0,
  "portside-residences": 0,
  "aura-residences": 0,
  "la-riviera": 0,
};
